import { Inter } from "next/font/google";
import "./globals.css";
import LeftSideBar from "./components/LeftSideBar/LeftSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-gray-200">
        <LeftSideBar/>
        {children}
        </body>
    </html>
  );
}
