import { Inter } from "next/font/google";
import LeftSideBar from "./components/LeftSideBar/LeftSideBar";
import NavBar from "./components/NavBar/NavBar";
import CategoriesSec from "./components/CategoriesSec/CategoriesSec";
import SettingsSec from "./components/SettingsSec/SettingsSec";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Duas Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-gray-200 gap-4 px-6">
        <LeftSideBar />
        <div className="w-full">
          <NavBar />
          <main className="grid grid-cols-4 gap-3">
            <div className="col-span-1">
              <CategoriesSec />
            </div>
            <div className="col-span-4 lg:col-span-3 flex gap-3">
              {children}
              <SettingsSec />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
